config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route index
  get "tasks", to: "tasks#index"

  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to:"tasks#update"

  delete "/tasks/:id", to: 'tasks#destroy', as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
      if @task.save
        redirect_to @task
      else
      render "new"
    end
  end

  def edit

  end

  def update
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">

<h1>Edit this task :</h1>

<%= form_for(@task) do |t| %>
  <div class="form-group">
    <%= t.label :title %>
    <%= t.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>
  <%= t.submit class: 'btn btn-primary' %>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">

<h1>Hello here are the tasks</h1>

<% @tasks.each do |task| %>
  <% if task.completed == true  %>
    <div>
      <input type="checkbox" id="task" name="task"
             checked>
      <label for="scales"><%= link_to task.title, task_path(task) %></label>
    </div>
    <% else %>
    <div>
      <input type="checkbox" id="task" name="task"
             >
      <label for="scales"><%= link_to task.title, task_path(task) %></label>
    </div>
  <% end %>
<% end %>

<button type="button" class="btn btn-success"><%= link_to "Add new task", tasks_new_url %></button>
</div>

app/views/tasks/new.html.erb
<div class="container">

<%= form_for(@task) do |t| %>
  <div class="form-group">
    <%= t.label :title %>
    <%= t.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>
  <%= t.submit class: 'btn btn-primary' %>
<% end %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<% if @task.completed == true  %>
  <div>
    <input type="checkbox" id="task" name="task"
           checked>
    <label for="scales">This task is completed</label>
  </div>
  <% else %>
  <div>
    <input type="checkbox" id="task" name="task" >
    <label for="scales">This task is not completed yet</label>
    <br>
    </div>
  </div>
  <% end %>


    <button type="button" class="btn btn-success"><%= link_to "Edit task", task_edit_url %></button>
      <br>
      <button type="button" class="btn btn-danger"><%= link_to "Delete task", task_delete_path(@task), method: :delete , data: {confirm: "Are you sure?"} %></button>